### PR TITLE
replace old style include guards with "#pragma once"

### PR DESCRIPTION
**Pull request by AlvaroBurnett**

### CODE REVIEW

**Comment by AlvaroBurnett** [comment]
I guess I should close the PR.

**Comment by bluewww** [comment]
What exactly is the point of using this (non-standard) feature instead of include guards?

**Comment by AlvaroBurnett** [comment]
-It is supported by all compilers.
-It saves you from putting an #endif at the end of the file.
-It doesn't introduce a new macro.
What is the point of using the old style include guards?

**Comment by bluewww** [comment]
Is not standard compliant. For me this already a big reason not to use it. Also there is subtle breakage when you start symlinking/copying headers.

**Comment by AlvaroBurnett** [comment]
It doesn't conflict with the standard. It' just something additional, just like the SDL library is used here even though it isn't standard. Can you explain the breakage issue please?

**Comment by bluewww** [comment]
Sorry I maybe didn't phrase it well enough: I mean #pragma once is not part of the standard, not that it is conflicting.
Regarding breakage If you include the same file through several locations (e.g. symlinked versions) and use pragma once then on some compilers that fails since these consider files with different paths different. I have to concede though that this is not a very common thing.

**Comment by AlvaroBurnett** [comment]
OK thanks. Seems that this issue comes from the fact that neither the Unix nor the Windows filesystem API offer any mechanism to tell whether two absolute pathnames refer to the same file. That's unfortunate.

**Pull request closed without merging**
